### PR TITLE
Introduce Jitter decorator

### PR DESCRIPTION
**Pull request by srijs**
Just to get my head around the existing code base, here is a small PR adding jitter functionality.

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Since the implementation doesn't keep any state between iterations, what about exposing it as a mapping function instead of a decorator so it can be used like this?

``` rust
Exponential::from_millis(1000).map(jitter)
```

**Comment by srijs** [comment]
Great idea! Growing really fond of the iterator as delay strategy API, makes so many things simpler.

Should it still live in the `delay` module or move it to the top-level instead?

**Comment by jimmycuadra** [comment]
Hmm, I could see it either way. I think the delay module would be slightly more appropriate, though.

**Comment by srijs** [comment]
Updated the PR with the changes. Agreed on the `delay` module

**Pull request merged**
