### PR TITLE
Implement retry exponentially

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi!
Thanks for providing the great crate. :blush: 
I want to use `wait_exponentially` feature in my crate, but I couldn't find `wait_exponentially` feature in your crate code.
So, I tried to implement this feature.

PS: How long  does it take to release new version which includes this feature?

### CODE REVIEW

**Comment by jimmycuadra** [comment]
Hey! Thanks for the contribution. I'm not totally sure about the implementation here. If the value of `wait` is a `u64`, doesn't that restrict the useful exponential curves the user can generate? I think it'd need to be an `f64`. Now that the variable `multiplier` is being used, it doesn't need to have a leading underscore, either. Also, `sleep_ms` is deprecated now, so we should switch to using `sleep` with a `Duration`. For the `retry_exponentially` function, the documentation should say, "Invokes a function a certain number of times or until a condition is satisfied with an exponential backoff after each unsuccessful try." Once your patch is merged, I can publish a new release to crates.io right away. :}

**Comment by cosmo0920** [comment]
> Also, sleep_ms is deprecated now, so we should switch to using sleep with a Duration.

I think we should not treat this issue in this PR.
A PR should contains one fixing issue or adding feature.

**Comment by cosmo0920** [comment]
Also I've fixed about `wait_exponentially` wait value type. (u32 -> f64)

**Comment by jimmycuadra** [comment]
Fair enough! Thanks for the work. I'll fix the sleep issue and then release a new crate shortly.

**Comment by cosmo0920** [comment]
Thanks for your advices!
I'm glad to contributes this great crate. :smile:

**Comment by jimmycuadra** [comment]
Released! https://github.com/jimmycuadra/retry/releases/tag/v0.4.0 The online rustdoc docs are updated too. Thanks again.

**Pull request merged**
